tests:
	gcc test_topuser.c -o test_topuser
	gcc test_timeuser.c -o test_timeuser
	gcc test_kernelps.c -o test_kernelps
	gcc test_pidtoname.c -o test_pidtoname

clean:
	rm test_topuser
	rm test_timeuser
	rm test_kernelps
	rm test_pidtoname
